{{- if .Values.server.autoscaling.enabled -}}
apiVersion: {{ .Values.server.autoscaling.apiVersion }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "trino.worker" . }}
  {{- if .Values.commonLabels }}
  labels:
    {{- tpl (toYaml .Values.commonLabels) . | nindent 4 }}
  {{- end }}
spec:
  maxReplicas: {{ .Values.server.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.server.workers }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "trino.worker" . }}
    {{- .Values.server.autoscaling.extraSpec | nindent 2 }}
{{- end }}
